### PR TITLE
Store std::shared_ptr objects instead of raw pointers.

### PR DESCRIPTION
**Pull request by bangerth**

### CODE REVIEW

**Review by dklong-csu — COMMENTED** [review]
The original setup used the fact that we always add an object derived from `RightHandSideContribution` using `add_rhs_contribution`. However, now `std::shared_ptr<RightHandSideContribution>` does not have such a clear relationship to `std::shared_ptr<TermolecularNucleation>` or the others. My IDE is suggesting casting `std::shared_ptr<...>` to `std::shared_ptr<RightHandSideContribution>` as a solution. Will this retain the correct `add_contribution_to_rhs` member function implemented in each derived class?

**Comment by bangerth** [comment]
Take a look at fae3d99 for how one needs to adjust things so that it now all works correctly.

**Comment by bangerth** [comment]
Seems to work now!

**Comment by dklong-csu** [comment]
I see! Thanks for your help!

**Pull request merged**
