### PR TITLE
Compute the mean value.

### PR DESCRIPTION
**Pull request by bangerth**
Here you go!

The samples I get are like this:
```
kf=0.036, kb=72700, k1=64500, k2=16300, k3=5560, w=3, maxsize=2500, n_variables=2501, particle_size_cutoff=274
kf=0.036, kb=72316.3, k1=65444.4, k2=15676.8, k3=6545.76, w=3, maxsize=2500, n_variables=2501, particle_size_cutoff=266
kf=0.036, kb=73309.3, k1=74798.3, k2=16128.4, k3=7507.98, w=3, maxsize=2500, n_variables=2501, particle_size_cutoff=275
kf=0.036, kb=73309.3, k1=74798.3, k2=16128.4, k3=7507.98, w=3, maxsize=2500, n_variables=2501, particle_size_cutoff=275
kf=0.036, kb=73309.3, k1=74798.3, k2=16128.4, k3=7507.98, w=3, maxsize=2500, n_variables=2501, particle_size_cutoff=275
kf=0.036, kb=73905.1, k1=72024.2, k2=15552.3, k3=7870.7, w=3, maxsize=2500, n_variables=2501, particle_size_cutoff=285
kf=0.036, kb=73905.1, k1=72024.2, k2=15552.3, k3=7870.7, w=3, maxsize=2500, n_variables=2501, particle_size_cutoff=285
kf=0.036, kb=73905.1, k1=72024.2, k2=15552.3, k3=7870.7, w=3, maxsize=2500, n_variables=2501, particle_size_cutoff=285
kf=0.036, kb=74650, k1=65006.5, k2=16540.4, k3=8514.51, w=3, maxsize=2500, n_variables=2501, particle_size_cutoff=288
kf=0.036, kb=73900.3, k1=70281.5, k2=16521.6, k3=8841.72, w=3, maxsize=2500, n_variables=2501, particle_size_cutoff=284
```
and it prints this for the mean:
```
kf=0.036, kb=73521, k1=70570, k2=16008.1, k3=7559.8, w=4294967295, maxsize=4294967295, n_variables=4, particle_size_cutoff=279.2
```

Since you don't vary the `const` parameters in the `Parameters` structure, you might as well remove outputting them in `operator<<` -- there is nothing for us to learn from seeing their values.

On my system, this runs for 3min26s, so pretty much exactly 20s per sample. (You get to see the run time if you run the executable via `time ./mepbm`.) You can make your runs faster if you do
```
cmake -DCMAKE_BUILD_TYPE=RELEASE .
make clean
make
```
Choosing the `RELEASE` build type enables compiler optimizations that aren't on by default. For me, the `RELEASE` build runs in about 2/3 the time of the default build.

It isn't exceedingly difficult to add histograms and covariance matrices to this, but how about you first run this overnight and we just look at the samples you have. The night has ~8 hours, so try whether you can reproduce the samples above and then pick something like 1500 samples?

### CODE REVIEW

**Comment by dklong-csu** [comment]
Great! When I run on down, I get the same samples as you (and I get the same on my personal machine). Weird error, though, is with the likelihoodReasonable test. The first part of the results are completely correct, however, the probability mass function is calculated to be 
`
2.39854e-09, 2.04805e-198,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
`
which is certainly not correct. This is strange because, for the log-likelihood to be correct, the pmf must have been calculated correctly during the initial function call. However, the bin counts and pmf output are created using code snippets from the likelihood function. The bin counts are correct, but it seems something went wrong with the pmf calculation. I haven't found the issue yet and I have a couple other things I need to do tonight, so I'm going to let the code run overnight for now just in case we find the error to be only in the test suite.

**Comment by bangerth** [comment]
Sounds good.

This is an example of what I described where it's useful to break one test up into a series of gradually more complicated ones, with the intermediate ones outputting intermediate information. This way you can check that the intermediate computations that you have verified on one machine are also correct on another machine. So if your current "Do A, then B, then C" test fails on one machine, you don't know where A, B, or C is wrong there. If you have one test that does "Do A", one that does "Do A then B", then one that does it all, and they all succeed on your machine, all you need to do is check which of these 3 tests fail on 'down' and you already know which operation you need to look into!

**Comment by bangerth** [comment]
In other words, debug this by creating more and more tests that should all go into the test suite. A test suite cannot have too many tests.

**Comment by dklong-csu** [comment]
I see your point with splitting up the tests now. I'll split up the tests and see where the error is (tomorrow).

**Comment by bangerth** [comment]
On 8/25/20 9:32 PM, dklong-csu wrote:
> I see your point with splitting up the tests now.

30 years of debugging experience ;-)

**Pull request merged**
